In [1]:
import numpy as np
from numpy.linalg import (svd,det,norm)

In [2]:
def wahbas_problem(ref_los, body_los):
	"""
		Returns R rotation matrix from body to reference frame
	"""
	A = ref_los.T
	E = body_los.T
	B = A@E.T
	U,S,V = svd(B)
	M = np.eye(3)
	M[2,2] = det(U)*det(V.T)
	return U@M@V

In [13]:
# Camera position
cam_pos = np.array([-731311.5,1658105,-358828.5])

# Target Position
target_pos = np.array([3.74150016e+08,5.14136479e+07,1.81379928e+07])

# Align Z axis with target
z_axis = target_pos-cam_pos
z_axis = z_axis/np.linalg.norm(z_axis)
#print(z_axis)

# Use y aligned with Moon center to find x axis
y_axis = cam_pos/np.linalg.norm(cam_pos)

# Calculate x axis
x_axis = np.cross(y_axis,z_axis)

# Recalculate y axis
y_axis = np.cross(z_axis,x_axis)

#print("X = {}".format(x_axis))
#print("Y = {}".format(y_axis))
#print("Z = {}".format(z_axis))

local = np.eye(3)
globl = np.array([x_axis,y_axis,z_axis])

R = wahbas_problem(local,globl)
print(R.T)

[[ 0.07233999 -0.12009505  0.99012328]
 [-0.18037696  0.97477941  0.13141258]
 [-0.98093378 -0.18810181  0.04885315]]
