# Notebook for Testing Quaternion Conversions

In [1]:
# Library imports
import numpy as np
import sys
from os.path import basename,dirname,abspath,join
SRC_DIR = join(dirname(abspath('')),"src")
sys.path.append(SRC_DIR)

# Local imports
from Structures import Quaternion,State

In [21]:
# DCM to Quaternion
in_dcm = input("Enter DCM: ")
dcm = in_dcm.replace("[","").replace("]","").strip().replace(","," ").replace("  "," ").replace("  "," ").replace("  "," ")
dcm = np.array(dcm.split(" "),dtype=float).reshape((3,3))
dcm2quat = Quaternion()
dcm2quat.fromDCM(dcm)
print(dcm2quat.toArray())

[ 0.72102797  0.14623454 -0.67570243  0.04647955]


In [18]:
# Quaternion to DCM
in_quat = input("Enter quaternion: ")
in_quat = in_quat.replace("[","").replace("]","").replace("  "," ").replace("  "," ").replace(" ",",").strip(",").split(",")
print(in_quat)
quat = Quaternion(s=in_quat[0],v=in_quat[1:4])
q2dcm = quat.toDCM()
print(q2dcm)

['0.72227662', '0.1399369', '-0.67527112', '0.05237432']
[[ 0.08253175 -0.11333319  0.99012327]
 [-0.26464818  0.95534918  0.13141257]
 [-0.96080687 -0.27288002  0.04885322]]


In [19]:
def RotZ(angle):
	return np.array([[np.cos(angle),-np.sin(angle),0],
									[np.sin(angle),np.cos(angle),0],
									[0,0,1]])

def RotY(angle):
	return np.array([[np.cos(angle),0,np.sin(angle)],
									[0,1,0],
									[-np.sin(angle),0,np.cos(angle)]])

def RotX(angle):
	return np.array([[1,0,0],
									[0,np.cos(angle),-np.sin(angle)],
									[0,np.sin(angle),np.cos(angle)]])

Rz = RotZ(np.deg2rad(-5))
Ry = RotY(np.deg2rad(5))
Rx = RotX(np.deg2rad(-1))

In [20]:
print(q2dcm@Rx)

[[ 0.08253175 -0.13059596  0.98799453]
 [-0.26464818  0.95291021  0.1480657 ]
 [-0.96080687 -0.27369107  0.04408337]]


In [ ]:
# Initial Quaternion
# [ 0.7238737   0.1103488  -0.68073237  0.02081921]

# Revised Quaternion
# [ 0.72227662  0.1399369  -0.67527112  0.05237432]

# + RotX -1
# [ 0.72102797  0.14623454 -0.67570243  0.04647955]